Signal handler <promise@0x2176ed4ea30 --> <bound method Celery._autodiscover_tasks of <Celery SocialApp at 0x2176eb67bf0>>> raised: ModuleNotFoundError("No module named 'models'")
Traceback (most recent call last):
  File "D:\CCNLTHD\Alumni-social-network_BE\SocialApp\venv\Lib\site-packages\celery\utils\dispatch\signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CCNLTHD\Alumni-social-network_BE\SocialApp\venv\Lib\site-packages\vine\promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "D:\CCNLTHD\Alumni-social-network_BE\SocialApp\venv\Lib\site-packages\vine\promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CCNLTHD\Alumni-social-network_BE\SocialApp\venv\Lib\site-packages\celery\app\base.py", line 694, in _autodiscover_tasks
    return self._autodiscover_tasks_from_fixups(related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CCNLTHD\Alumni-social-network_BE\SocialApp\venv\Lib\site-packages\celery\app\base.py", line 703, in _autodiscover_tasks_from_fixups
    return self._autodiscover_tasks_from_names([
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CCNLTHD\Alumni-social-network_BE\SocialApp\venv\Lib\site-packages\celery\app\base.py", line 698, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CCNLTHD\Alumni-social-network_BE\SocialApp\venv\Lib\site-packages\celery\loaders\base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CCNLTHD\Alumni-social-network_BE\SocialApp\venv\Lib\site-packages\celery\loaders\base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CCNLTHD\Alumni-social-network_BE\SocialApp\venv\Lib\site-packages\celery\loaders\base.py", line 278, in find_related_module
    raise e
  File "D:\CCNLTHD\Alumni-social-network_BE\SocialApp\venv\Lib\site-packages\celery\loaders\base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LAPTOP\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\CCNLTHD\Alumni-social-network_BE\SocialApp\Sociales\tasks.py", line 6, in <module>
    from models import *
ModuleNotFoundError: No module named 'models'
